### ISSUE TITLE
About PhyBench: A Physical Commonsense Benchmark for Evaluating Text-to-Image Models

### ISSUE THREAD

**Issue by Redtides0** [OpenGVLab/PhyGenBench#3]
Hi, why was the Phybench repository deleted?

**Comment by FanqingM** [comment]
Actually, We just temporarily hide this repo... Because:
For the T2I version, we think that we need to make some  changes to the dataset and evaluation framework.
Mainly
1. Some cases can be solved by prompt engineering, which makes the entire benchmark too simple
2. Some prompts are ambiguous

We will modify it ASAP

**Comment by hithqd** [comment]
When will PyBench be reopened and the data released?
